### ISSUE TITLE
New check for Virtual Log File Count

### ISSUE THREAD

**Issue by vpnicholls** [Teutenberg/DBAid2#13]
A new check is required to get the VLF count for each database (system and user) and alert if above a certain threshold. The threshold must be configurable. Suggested defaults would be 50-99 for WARNING and 100+ for CRITICAL.

There must be an override (e.g. a value of 0) for cases where we do not want to monitor the VLF count.

**Comment by Teutenberg** [comment]
There is a new health schema that has a stored procedure called, "[health].[get_transaction_log]". This will give you details about VLF counts. I don't think we would want to actively monitor this.
