### ISSUE TITLE
Add script to monitor for unused databases

### ISSUE THREAD

**Issue by thecosmictrickster** [Teutenberg/DBAid2#17]
Requested by Glenn Brinfield. See "SQL Connection Logging" under BADP/SQL/Consulting in Gitlab.

**Comment by Teutenberg** [comment]
There is an audit procedure that can be executed as an agent job to capture database last access times. I'm pretty sure this covers the requirement, but if not, please provide more detail?

https://github.com/Teutenberg/DBAid2/blob/master/database/audit/procedures/get_database_last_access.sql

**Comment by thecosmictrickster** [comment]
It's not quite the same. The DBAid procedure captures whether a database has been accessed. The [SQL Connection Logging] stuff captures additional useful information like hostname, program name, and login name which can help further determine if a database may still be "in use" when in fact it & the related application could both be decommissioned.
