### ISSUE TITLE
Transaction Log Backup Not Performed Within x Hours

### ISSUE THREAD

**Issue by thecosmictrickster** [Teutenberg/DBAid2#18]
For databases in bulk or full recovery mode, we sometimes want to be alerted if a transaction log backup has not started within a given period.

Transferred from DBAid issues.

**Comment by Teutenberg** [comment]
Transaction log backups should raise an event if not backed up within 1 hour. 

https://github.com/Teutenberg/DBAid2/blob/master/database/checkmk/procedures/check_backup.sql#L60
https://github.com/Teutenberg/DBAid2/blob/master/database/checkmk/tables/config_database.sql#L18
