### ISSUE TITLE
Collector can't handle archive ERRORLOG files missing

### ISSUE THREAD

**Issue by thecosmictrickster** [Teutenberg/DBAid2#2]
Normal ERRORLOG archiving goes something like:

ERRORLOG
ERRORLOG.1
ERRORLOG.2
ERRORLOG.3

If there is a file missing, Collector crashes. E.g. if sequence is like:

ERRORLOG
ERRORLOG.1
ERRORLOG.3
ERRORLOG.4

**Comment by Teutenberg** [comment]
xp_fileexist is ok to use even though undocumented. Don't use xp_cmdshell, we don't want to be toggling configuration settings on and off.

**Comment by Teutenberg** [comment]
If you delete an errorlog is it still reported in [xp_enumerrorlogs]? If not, then we should not increment a loop by ++1, we should use the archive numbers provided by [xp_enumerrorlogs].

**Comment by Teutenberg** [comment]
```
DECLARE @enumerrorlogs TABLE ([archive] INT,[date] DATETIME,[file_size_byte] BIGINT);
DECLARE @archive INT,
	@start_datetime DATETIME = NULL,
	@end_datetime DATETIME = NULL

INSERT INTO @enumerrorlogs
	EXEC [master].[dbo].[xp_enumerrorlogs];

DECLARE curse CURSOR FAST_FORWARD FOR SELECT [archive] FROM @enumerrorlogs ORDER BY [date] DESC;
OPEN curse;
FETCH NEXT FROM curse INTO @archive;

WHILE (@@FETCH_STATUS = 0)
BEGIN
	EXEC [master].[dbo].[xp_readerrorlog] @archive, 1, NULL, NULL, @start_datetime, @end_datetime;

	IF (@@ROWCOUNT = 0)
	BEGIN
		BREAK;
	END

	FETCH NEXT FROM curse INTO @archive;
END

CLOSE curse;
DEALLOCATE curse;
```

**Comment by thecosmictrickster** [comment]
> 
> 
> If you delete an errorlog is it still reported in [xp_enumerrorlogs]? If not, then we should not increment a loop by ++1, we should use the archive numbers provided by [xp_enumerrorlogs].

It looks like [xp_enumerrorlogs] is some sort of internal tracking and doesn't reflect what's actually on the disk, only what SQL Server thinks is there. Presumably the loop that renames them when DBCC ERRORLOG or the like is run manages to handle gaps a bit better; I've not seen errors when it's run.

**Comment by Teutenberg** [comment]
Tested in SQL 2017, [xp_enumerrorlogs] returns only the errorlog files on disk. Updated proc to use archive number.
